-- ETL target schema. Portable SQL: PostgreSQL and H2 in PostgreSQL mode.
-- (Spring Batch's own BATCH_* metadata tables are managed separately by Boot.)

-- Staging: one row per airport/checkpoint/hour, straight from validated CSV rows.
CREATE TABLE throughput_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_date     DATE        NOT NULL,
    airport         VARCHAR(3)  NOT NULL,
    checkpoint      VARCHAR(50) NOT NULL,
    hour_of_day     INT         NOT NULL,
    passenger_count INT         NOT NULL,
    source_file     VARCHAR(255) NOT NULL,
    loaded_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_throughput_date_airport ON throughput_records (record_date, airport);

-- Warehouse: recomputed by the aggregation step after every load.
CREATE TABLE daily_airport_summary (
    summary_date          DATE       NOT NULL,
    airport               VARCHAR(3) NOT NULL,
    total_passengers      BIGINT     NOT NULL,
    checkpoints_reporting INT        NOT NULL,
    avg_hourly_passengers INT        NOT NULL,
    PRIMARY KEY (summary_date, airport)
);

-- Quarantine: rows the pipeline refused, with the reason, for audit and replay.
CREATE TABLE rejected_records (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file VARCHAR(255) NOT NULL,
    raw_content VARCHAR(1000),
    reason      VARCHAR(500) NOT NULL,
    rejected_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
